# Generated by Django 5.1.5 on 2025-02-02 12:30

import PaymentGateway.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField()),
                ('merchant_id', models.CharField(max_length=50)),
                ('API_key', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('national_code', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('wallet_uuid', models.UUIDField()),
                ('status', models.CharField(choices=[(PaymentGateway.models.PaymentStatus['PENDING'], 'pending'), (PaymentGateway.models.PaymentStatus['COMPLETED'], 'completed'), (PaymentGateway.models.PaymentStatus['FAILED'], 'failed')], default='pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='PaymentGateway.paymentgateway')),
            ],
        ),
    ]
